name: push-pr-build-linux
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.0.0.java11'
      - name: Install native-image
        run: gu install native-image
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="1.0.0" 
      - name: Build native executable
        run: ./mvnw package -Dnative 
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: commit-${{ github.sha}}-${{ github.run_id }}
          release_name: Release commit-${{ github.sha }}-${{ github.run_id }}
          draft: false
          prerelease: false

      - name: Upload native executable
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/starfish-1.0.0-runner
          asset_name: starfish-runner-linux
          asset_label: linux
          asset_content_type: application/octet-stream
